### ISSUE TITLE
Question about twrp.dependencies

### ISSUE THREAD

**Issue by remtrik** [Mi-Thorium/twrp_device_xiaomi_mi439#1]
Maybe it's `"repository": "twrp_device_xiaomi_mithorium-common"` and not `"repository": "android_device_xiaomi_mithorium-common"` ?

Also same might apply to [https://github.com/Mi-Thorium/twrp_device_xiaomi_mithorium-common/blob/android-12.1/twrp.dependencies](url) where it might be a `twrp_device_xiaomi_kernel-mithorium`

**Comment by me-cafebabe** [comment]
Yes, but that repository name is used by ROM device tree in this organization, so I had to change it to something else. BTW, This device tree is also available in official TeamWin organization now
